### ISSUE TITLE
Unable to compile TcpServer example in Arduino 1.5.4 and 1.5.5

### ISSUE THREAD

**Issue by Sam2D** [ntruchsess/arduino_uip#23]
Compiles fine in Arduino 1.0.5, but not the newer releases.

TcpServer (and others) -

Arduino: 1.5.5 (Mac OS X), Board: "Arduino Pro or Pro Mini, ATmega328 (5V, 16 MHz)"

TcpServer:23: error: 'EthernetServer' does not name a type
TcpServer.ino: In function 'void setup()':
TcpServer:30: error: 'IPAddress' was not declared in this scope
TcpServer:30: error: expected `;' before 'myIP'
TcpServer:32: error: 'Ethernet' was not declared in this scope
TcpServer:32: error: 'myIP' was not declared in this scope
TcpServer:34: error: 'server' was not declared in this scope
TcpServer.ino: In function 'void loop()':
TcpServer:41: error: 'EthernetClient' was not declared in this scope
TcpServer:41: error: expected`)' before 'client'
TcpServer:43: error: 'client' was not declared in this scope
TcpServer:50: error: 'client' was not declared in this scope

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
